export const GET_ALL_TESTS_SUCCESS = 'GET_ALL_TESTS_SUCCESS';
export const GET_ALL_TESTS_FAIL = 'GET_ALL_TESTS_FAIL';

export const RUN_TEST_SUCCESS = 'RUN_TEST_SUCCESS';
export const RUN_TEST_FAIL = 'RUN_TEST_FAIL';
